
CREATE DATABASE leonnie;


USE leonnie;


CREATE TABLE IF NOT EXISTS LOGIN (
	id_login INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	nom_login VARCHAR(255) NOT NULL,
	mdp_login VARCHAR(255) NOT NULL,
	PRIMARY KEY (id_login)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS COULEUR (
	id_couleur INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	nom_couleur VARCHAR(255) NOT NULL,
	PRIMARY KEY (id_couleur)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS TYPE_PRODUIT(
	id_type INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	type_produit VARCHAR(255) NOT NULL,
	id_categorie CHAR(5) DEFAULT 'meubl' NOT NULL,
	PRIMARY KEY (id_type)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;


CREATE TABLE IF NOT EXISTS MEDIA (
	id_media INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	titre_media VARCHAR(255) NOT NULL,
	type_media VARCHAR(255) NOT NULL,
	extension_media VARCHAR(15) NOT NULL,
	PRIMARY KEY (id_media)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS RUBRIQUE (
	id_rubrique INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	titre_rubrique VARCHAR(255) NOT NULL,
	PRIMARY KEY (id_rubrique)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;	

CREATE TABLE IF NOT EXISTS PRODUIT (
	id_produit INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	titre_produit VARCHAR(255) NOT NULL,
	prix_produit FLOAT UNSIGNED NOT NULL,
	materiau_produit TEXT NOT NULL,
	txt_produit TEXT NOT NULL,
	id_type INTEGER UNSIGNED NOT NULL,
	id_couleur INTEGER UNSIGNED NOT NULL,
	PRIMARY KEY (id_produit),
	FOREIGN KEY (id_type) REFERENCES TYPE_PRODUIT (id_type),
	FOREIGN KEY (id_couleur) REFERENCES COULEUR (id_couleur)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS LANGUE (
	id_langue INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	nom_langue VARCHAR(40) NOT NULL,
	PRIMARY KEY (id_langue)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;
	
CREATE TABLE IF NOT EXISTS ARTICLE (
	id_article INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	date_article VARCHAR(255) NOT NULL,
	titre_article VARCHAR(255) NOT NULL,
	txt_article TEXT NOT NULL,
	id_rubrique INTEGER UNSIGNED NOT NULL,
	id_media INTEGER UNSIGNED NOT NULL,
	id_produit INTEGER UNSIGNED NOT NULL,
	id_decoration INTEGER UNSIGNED NOT NULL,
	id_langue INTEGER UNSIGNED NOT NULL,
	PRIMARY KEY (id_article),
	FOREIGN KEY (id_rubrique) REFERENCES RUBRIQUE (id_rubrique),
	FOREIGN KEY (id_media) REFERENCES MEDIA (id_media),
	FOREIGN KEY (id_produit) REFERENCES produit (id_produit),
	FOREIGN KEY (id_langue) REFERENCES LANGUE (id_langue)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS RSS (
	id_rss INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	link_rss VARCHAR(255) NOT NULL,
	guid_rss VARCHAR(255) NOT NULL,
	pubdate_rss VARCHAR(255) NOT NULL,
	id_article INTEGER UNSIGNED NOT NULL,
	PRIMARY KEY (id_rss),
	FOREIGN KEY (id_article) REFERENCES ARTICLE (id_article)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

